server.port=8090

platform.booking.version = ${PLATFORM_VERSION:/v1}

spring.datasource.url=jdbc:postgresql://localhost:5432/platform
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=java
spring.datasource.username=postgres


spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
spring.flyway.schemas=booking

springdoc.swagger-ui.path = /api${platform.booking.version}/booking-service/openapi/swagger-ui.html
springdoc.api-docs.path = /api${platform.booking.version}/booking-service/openapi/api-docs